### ISSUE TITLE
Error executing vim.schedule lua callback

### ISSUE THREAD

**Issue by DartMitai** [hrsh7th/nvim-cmp#1630]
### Discussed in https://github.com/hrsh7th/nvim-cmp/discussions/1627

<div type='discussions-op-text'>

<sup>Originally posted by **DartMitai** June 18, 2023</sup>
after the update, I get an error when switching to command mode
```
Error executing vim.schedule lua callback: vim/shared.lua:0: t: expected table, got boolean
stack traceback:
        [C]: in function 'error'
        vim/shared.lua: in function 'validate'
        vim/shared.lua: in function 'tbl_contains'
        ...e/mitai/.local/share/nvim/lazy/nvim-cmp/lua/cmp/core.lua:169: in function 'autoinde
nt'
        ...e/mitai/.local/share/nvim/lazy/nvim-cmp/lua/cmp/core.lua:162: in function 'on_chang
e'
        ...e/mitai/.local/share/nvim/lazy/nvim-cmp/lua/cmp/init.lua:304: in function 'callback
'
        .../.local/share/nvim/lazy/nvim-cmp/lua/cmp/utils/async.lua:165: in function <.../.loc
al/share/nvim/lazy/nvim-cmp/lua/cmp/utils/async.lua:163>
```

my config

```
local cmp = require('cmp')
local lspkind = require('lspkind')
local luasnip = require('luasnip')


require("luasnip/loaders/from_vscode").lazy_load { paths = { "/home/mitai/.config/nvim/lua/snippets" } }
require("luasnip").filetype_extend("dart", { "flutter" })

local source_mapping = {
  luasnip = '[snip]',
  buffer = "[buf]",
  nvim_lsp = "[lsp]",
  path = "[path]"
}

cmp.setup {
  snippet = {
    expand = function(args)
      luasnip.lsp_expand(args.body)
    end
  },
  window = {
    completion = cmp.config.window.bordered(),
    documentation = cmp.config.window.bordered(),
  },
  mapping = cmp.mapping.preset.insert({
    ['<C-b>'] = cmp.mapping.scroll_docs(-4),
    ['<C-f>'] = cmp.mapping.scroll_docs(4),
    ['<C-Space>'] = cmp.mapping.complete(),
    ['<C-c>'] = cmp.mapping.abort(),
    ['<CR>'] = cmp.mapping.confirm({ select = true }), -- Accept currently selected item. Set `select` to `false` to only confirm explicitly selected items.
  }),

  sources = cmp.config.sources {
    { name = 'nvim_lsp' },
    {
      name = 'luasnip',
      keyword_length = 2,
      priority = 50,
    },
    { name = 'buffer' },
    { name = 'path' },
    { name = 'nvim_lsp_signature_help' }
  },
  experimental = {
    -- New menu, better than the old menu
    native_menu = false,
    -- "ghost" completion
    ghost_text = true,
  },
}

-- Use buffer source for `/`.
cmp.setup.cmdline('/', {
  completion = { autocomplete = false },
  sources = {
    -- { name = 'buffer' }
    { name = 'buffer', opts = { keyword_pattern = [=[[^[:blank:]].*]=] } }
  }
})

-- Use cmdline & path source for ':'.
cmp.setup.cmdline(':', {
  completion = { autocomplete = true },
  sources = cmp.config.sources({
    { name = 'path' }
  }, {
    { name = 'cmdline' }
  })
})
```

https://github.com/MitaiDart/dotfiles/blob/master/nvim/lua/plugins/cmp.lua</div>

**Comment by hrsh7th** [comment]
You can't specify `autocomplete = true` it should be `autocomplete = { cmp.TriggetEvent.TextChanged }` instead.

**Comment by rickalex21** [comment]
I am getting a similar error:

```text
Error executing vim.schedule lua callback: function cmp_nvim_ultisnips#get_current_snippets[33]..provider#python3#Call, line 18: Vim(return):Error invoking 'python_execute' on channel 6 (pyth
on3-script-host):                                                                                                                                                                              
Traceback (most recent call last):                                                                                                                                                             
  File "<string>", line 22, in <module>                                                                                                                                                        
  File "/usr/lib/python3.12/site-packages/pynvim/api/nvim.py", line 287, in command                                                                                                            
    return self.request('nvim_command', string, **kwargs)                                                                                                                                      
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                                      
  File "/usr/lib/python3.12/site-packages/pynvim/api/nvim.py", line 182, in request                                                                                                            
    res = self._session.request(name, *args, **kwargs)                                                                                                                                         
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                                         
  File "/usr/lib/python3.12/site-packages/pynvim/msgpack_rpc/session.py", line 102, in request                                                                                                 
    raise self.error_wrapper(err)                                                                                                                                                              
pynvim.api.common.NvimError: Vim:<action-code>:1: SyntaxWarning: invalid escape sequence '\e'                                                                                                  
stack traceback:                                                                                                                                                                               
        [C]: in function 'load_snippets'                                                                                                                                                       
        ...ged/cmp-nvim-ultisnips/lua/cmp_nvim_ultisnips/source.lua:27: in function 'complete'                                                                                                 
        ...ritchie/.config/nvim/plugged/nvim-cmp/lua/cmp/source.lua:334: in function 'complete'                                                                                                
        ...e/ritchie/.config/nvim/plugged/nvim-cmp/lua/cmp/core.lua:299: in function 'complete'                                                                                                
        ...e/ritchie/.config/nvim/plugged/nvim-cmp/lua/cmp/core.lua:169: in function 'autoindent'                                                                                              
        ...e/ritchie/.config/nvim/plugged/nvim-cmp/lua/cmp/core.lua:161: in function 'on_change'                                                                                               
        ...e/ritchie/.config/nvim/plugged/nvim-cmp/lua/cmp/init.lua:338: in function 'callback'                                                                                                
        ...ie/.config/nvim/plugged/nvim-cmp/lua/cmp/utils/async.lua:165: in function <...ie/.config/nvim/plugged/nvim-cmp/lua/cmp/utils/async.lua:163>       
```
